name: first workflow
on: push
jobs: 
   my-job:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v4
       - name: Read-File
         run: cat demo.txt